/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        approved: "var(--approved)",
        "body-background": "var(--body-background)",
        "body-color-2": "var(--body-color-2)",
        grey: "var(--grey)",
        lightbackgroundblue: "var(--lightbackgroundblue)",
        lightbackgroundprimary: "var(--lightbackgroundprimary)",
        lightbluebase: "var(--lightbluebase)",
        "lightgrayscale-100": "var(--lightgrayscale-100)",
        "lightgrayscale-200": "var(--lightgrayscale-200)",
        "lightgrayscale-300": "var(--lightgrayscale-300)",
        "lightgrayscale-400": "var(--lightgrayscale-400)",
        lightredbase: "var(--lightredbase)",
        "neutral-100": "var(--neutral-100)",
        "neutral-200": "var(--neutral-200)",
        "neutral-line": "var(--neutral-line)",
        "neutral-line-200": "var(--neutral-line-200)",
        "primary-base-color": "var(--primary-base-color)",
        "primary-color": "var(--primary-color)",
        secondary: "var(--secondary)",
        "secondary-base": "var(--secondary-base)",
        success: "var(--success)",
        "success-base": "var(--success-base)",
        warning: "var(--warning)",
        "warning-base": "var(--warning-base)",
        white: "var(--white)",
      },
      fontFamily: {
        "body-1": "var(--body-1-font-family)",
        "body-1-bold": "var(--body-1-bold-font-family)",
        "body-1-medium": "var(--body-1-medium-font-family)",
        "body-2": "var(--body-2-font-family)",
        "body-2-medium": "var(--body-2-medium-font-family)",
        "body-3": "var(--body-3-font-family)",
        "body-3-bold": "var(--body-3-bold-font-family)",
        "body-4": "var(--body-4-font-family)",
        "body-4-bold": "var(--body-4-bold-font-family)",
        "button-0": "var(--button-0-font-family)",
        "button-1": "var(--button-1-font-family)",
        "button-1-bold": "var(--button-1-bold-font-family)",
        "button-2": "var(--button-2-font-family)",
        "button-2-bold": "var(--button-2-bold-font-family)",
        "button-3": "var(--button-3-font-family)",
        "button-3-bold": "var(--button-3-bold-font-family)",
        "caps-caps-3-10-semi-bold": "var(--caps-caps-3-10-semi-bold-font-family)",
        "card-button": "var(--card-button-font-family)",
        h1: "var(--h1-font-family)",
        "h1-bold": "var(--h1-bold-font-family)",
        h2: "var(--h2-font-family)",
        "h2-bold": "var(--h2-bold-font-family)",
        h3: "var(--h3-font-family)",
        "h3-bold": "var(--h3-bold-font-family)",
        h4: "var(--h4-font-family)",
        "h4-bold": "var(--h4-bold-font-family)",
        "h4-medium": "var(--h4-medium-font-family)",
        h5: "var(--h5-font-family)",
        "h5-bold": "var(--h5-bold-font-family)",
        "h5-semi-bold": "var(--h5-semi-bold-font-family)",
        h6: "var(--h6-font-family)",
        "h6-bold": "var(--h6-bold-font-family)",
        "heading-h5-16": "var(--heading-h5-16-font-family)",
        "heading-h6-13": "var(--heading-h6-13-font-family)",
        "paragraph-p2-16": "var(--paragraph-p2-16-font-family)",
        "paragraph-p3-13": "var(--paragraph-p3-13-font-family)",
      },
      boxShadow: {
        "light-drop-shadow-1": "var(--light-drop-shadow-1)",
        "light-drop-shadow-2": "var(--light-drop-shadow-2)",
      },
    },
  },
  plugins: [],
};
